### PR TITLE
adding title to document in head element as a test for branching safely

### PR DESCRIPTION
**Pull request by jacksonMorrisThring**
I edited test.html and just changed the title from "document" to "Simulated Stargazing Environment'

### CODE REVIEW

**Comment by jacksonMorrisThring** [comment]
Hey guys, just testing what branching and merging is like on github. This is a test comment below my merge request

**Comment by Hongnodie** [comment]
Nice try

**Comment by jacksonMorrisThring** [comment]
Did I do something wrong Gan?

**Comment by jacksonMorrisThring** [comment]
@Hongnodie ^^^

**Review by mattyd96 — APPROVED** [review]
This is my review comment looking at and approving the pull request.

**Pull request merged**
